name: UnlimitedAnvilEnchants
version: '${project.version}'
main: github.curtisdh.unlimitedanvilenchants.UnlimitedAnvilEnchants
api-version: 1.17
commands:
  reloadConfig:
    description: Reloads the config file for 'UnlimitedAnvilEnchants'
    usage: /reloadConfig
    aliases: rcfg