name: TestProject
version: '${project.version}'
main: me.curtisdh.testproject.TestProject
api-version: 1.17
commands:
  reloadConfig:
    description: Reloads the config file for 'UnlimitedAnvilEnchants'
    usage: /reloadConfig
    aliases: rcfg

